### ISSUE TITLE
MVP - File Editor

### ISSUE THREAD

**Issue by 3ygun** [signofthehorns/watson-ta#1]
# Goals

Create our mvp file upload and editing interface. Similar to the mock-up: 
![watson ta](https://cloud.githubusercontent.com/assets/5482320/22273161/cfbb9994-e26c-11e6-8a4b-d39b4885a5d1.png)

# Parts

**Notice**: I originally though we'd do more stuff client side in JavaScript instead we're doing server side processing in Python. As such must of the suggested tools are irrelevant but I'm leaving them just in case. The main points are still accurate:

- [x] File upload & parsing (only allow `.pdf` uploads to make easy parsing?)
    - Use [PDF.js by Mozilla](https://github.com/mozilla/pdf.js) for parsing
- [x] File download on editing completion (`.pdf`)
- [x] Editing (and live update?)
    - Use [PDFmake Javascript Library](https://github.com/bpampuch/pdfmake) as it has a nicer usage interface than [jsPDF](https://github.com/MrRio/jsPDF) just look at the examples of both. Also the PDFmake's demo actually loads on Firefox which is a plus
- [x] UI with navigation and and movement >> Using [Bootstrap 4](https://v4-alpha.getbootstrap.com/components/navbar/) the shinny new Bootstrap because we wanted the flex-boxes ❤️.  Just normal CSS not SCSS as we currently don't have too many styles....
    - Preferred if we use [Bootstrap](https://getbootstrap.com/) in SCSS version however if someone has another prettier CSS library that is fine
- [x] Dynamic updates on the page >> We've chosen [ReactJS](https://facebook.github.io/react/) due to its ubiquity over Vue & familiarity to the Facebook crew  
    - One of [ReactJS](https://facebook.github.io/react/), [VueJS](https://vuejs.org/), other...

**Comment by tylermzeller** [comment]
What is MVP?

**Comment by 3ygun** [comment]
An [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) is a minimum viable product (e.g. what we place on Steam Early Access and never update again!)

**Comment by tylermzeller** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10216503-235097513_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by 3ygun** [comment]
Submitted API v0.1.0 pull request in #18

**Comment by 3ygun** [comment]
# Design

Bill created an updated code version of the File Editing interface mainly just a bunch of nice CSS with limited function.

![billsupdatedcodefileeditorrendering](https://cloud.githubusercontent.com/assets/5482320/23328301/f79d7bb6-faeb-11e6-83fe-4ab4d6f32911.PNG)

# Implementation

We've decided to do mainly server side process in python of pdf parsing etc. An updated list of current objectives are as follows:

1. [x] Convert to React Components (desired MVP order)
    1. Editor
    2. FileUpload
    3. Retrieve and Rank
    4. File Nav & User State
    5. Watson TA Chat interface
2. [x] Tie together functionality with [flux](https://facebook.github.io/flux/)
3. [x] Profit!

**Comment by 3ygun** [comment]
We've completed our desired:

1. Upload PDF
2. Parse & classify
3. Edit with knowledge base help
4. Export when finished #49
