### ISSUE TITLE
Team Bitmojis missing from Readme [Pr10r1ty: bigly]

### ISSUE THREAD

**Issue by tylermzeller** [signofthehorns/watson-ta#33]
![bitmoji](https://render.bitstrips.com/v2/cpanel/8706172-235097513_2-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by dltn** [comment]
beautiful

**Comment by dltn** [comment]
https://github.com/signofthehorns/watson-ta/pull/34

**Comment by 3ygun** [comment]
Completed with #37
