### ISSUE TITLE
Question Parsing Accuracy

### ISSUE THREAD

**Issue by 3ygun** [signofthehorns/watson-ta#38]
# Goal

Parsing isn't the best right now we should improve it!

# History

Old extract question method
```python
def extract_questions(text):
    text = text.replace('\t', ' ')
    pattern = '[0-9]+(\)|\.)(?:(?![0-9]+(\)|\.)).)*'
    res = [match.group(0) for match in re.finditer(pattern, text)]
    obj_res = []
    for r in res:
        rmap = {
            'class_name': 'TF',
            'confidence': 0.0
        }
        # todo get classified result
        obj_res.append(Classified(r[4:-1], rmap).get_map_repr())
    # order questions and classify
    return obj_res
```

# Regex Attempts
Had some example cases [here](https://regex101.com/r/wgRhAy/3)

## MC Choices Parsing
- Attempt at ABCD and abcd resolution: `(?P<choice>(?:.(?!(([ABCD][\.\)\:])|([abcd][\)\:]))))*)`

## Parse out question
- Mostly works but gets extra `(?:(\d+[\.](.(?!(\d+[\.])))*))`
- Doesn't split on lines `(?:(\d+[\.].*))`
- Final working `(\d+\..+?(?:(?=(?:\d+\.))|(\n|\r)))`
    - Parses number questions for splitting! 🌵

**Comment by tylermzeller** [comment]
Has document conversion helped at all?

**Comment by 3ygun** [comment]
No idea. We don't, to my knowledge, have any "previous data".

e.g. As we didn't try to see how it would render the answers in the past. This is the current main problem (see the `data/3-question.pdf` example on the `question-render` branch) in which the question becomes separate from the answers.

**Comment by 3ygun** [comment]
# Main Pieces

- [x] Multiple choice `MC` rendering
- [x] Make sure demo stuff is categorized correctly
- [ ] ~Add way to change question classification?~ Placing in UI tweeks
- [x] Better classification with #53

**Comment by 3ygun** [comment]
Completed closing.
